export enum ETechnologies {
  Angular = 'Angular',
  AngularJS = 'AngularJS',
  Typescript = 'Typescript',
  HTML = 'HTML',
  SCSS = 'SCSS',
  Git = 'Git',
  Github = 'Github',
  GraphQL = 'GraphQL',
  Rest = 'Rest',
  DevOps = 'DevOps',
  UnitTest = 'Unit Test',
  Flame = 'Flame Design System',
  Karma = 'Karma',
  Jasmine = 'Jasmine',
  Microapps = 'Microapps',
  MVVM = 'MVVM Design Pattern',
  Gilab = 'Gilab',
  JSP = 'JSP',
  Dotnet = '.NET',
}
